project = "KCNet ReVC Lua"
title = "API for KCNet ReVC"
description = "This is the custom lua scripts for my ReVC build."

file = {
    "freeroam-blips.lua",
    "freeroam-functions.lua",
    "freeroam-game.lua",
    "freeroam-garages.lua",
    "freeroam-objects.lua",
    "freeroam-pickups.lua",
    "kcnet-keybind-events.lua",
    "kcnet-busted.lua",
    "kcnet-wasted.lua",
}

dir = "docs"
format = "markdown"
