
-- List of enums for future use in my Lua scripts.

-- Source - https://stackoverflow.com/a/77170992
-- Posted by Maldus
-- Retrieved 2026-09-06, License - CC BY-SA 4.0

-- Testing with an enum in lua.

local enum = function(keys)
    local Enum = {}
    for _, value in ipairs(keys) do
        Enum[value] = {}
    end
    return Enum
end

local Result = enum { "Success", "Failure" }

-- Tables to be read from other files.

audio_enums = {}

camera_enums = {}

event_enums = {}

font_enums = {}

config_enums = {}

garage_enums = {}

stat_enums = {}

radar_enums = {}

weapon_enums = {}

weather_enums = {}

world_enums = {}

-- clothes_enums = {}

player_enums = {}
player_info_enums = {}

ped_enums = {}

-- vehicle_enums = {}

--------------
--- Custom enums below
--------------
---

custom_save = {}

-- These should match what is set in the games code.
-- If this is changed, loading/saving might not work.
custom_save.eSaveVersion = {
	save_format = "revc-freeroam",
	save_version = 1
}

-- misc_enums.h
--------------
---

--- The types for the stats.
--- Mostly used for my lua scripts.
stat_enums.eStatType = {
    SEAGULLS_KILLED = 0,
    DAYS_PASSED = 1,
    HEADS_POPPED = 2,
    COMMERCIAL_PASSED = 3,
    INDUSTRIAL_PASSED = 4,
    SUBURBAN_PASSED = 5,
    NUMBER_KILL_FRENZIES_PASSED = 6,
    PEOPLE_KILLED_BY_OTHERS = 7,
    HELIS_DESTROYED = 8,
    TIMES_DIED = 9,
    TIMES_ARRESTED = 10,
    KILLS_SINCE_LAST_CHECKPOINT = 11,

    DISTANCE_TRAVELLED_BY_CAR = 12,
    DISTANCE_TRAVELLED_BY_HELICOPTOR = 13,
    DISTANCE_TRAVELLED_BY_BIKE = 14,
    DISTANCE_TRAVELLED_BY_BOAT = 15,
    DISTANCE_TRAVELLED_BY_PLANE = 16,
    DISTANCE_TRAVELLED_BY_GOLF_CART = 17,
    DISTANCE_TRAVELLED_ON_FOOT = 18,

    FLIGHT_TIME = 19,
    TIMES_DROWNED = 20,
    PHOTOS_TAKEN = 21,

    LOAN_SHARKS = 22,
    STORES_KNOCKED_OFF = 23,
    MOVIE_STUNTS = 24,
    ASSASSINATIONS = 25,
    PIZZAS_DELIVERED = 26,
    GARBAGE_PICKUPS = 27,
    ICE_CREAM_SOLD = 28,
    TOP_SHOOTING_RANGE_SCORE = 29,
    SHOOTING_RANK = 30,

    CARS_EXPLODED = 31,
    BOATS_EXPLODED = 32,
    WANTED_STARS_ATTAINED = 33,
    WANTED_STARS_EVADED = 34,
    PEOPLE_KILLED_BY_PLAYER = 35,

    PROGRESS_MADE = 36,
    TOTAL_PROGRESS_IN_GAME = 37,
    MAXIMUM_JUMP_DISTANCE = 38,
    MAXIMUM_JUMP_HEIGHT = 39,
    MAXIMUM_JUMP_FLIPS = 40,
    MAXIMUM_JUMP_SPINS = 41,
    BEST_STUNT_JUMP = 42,
    NUMBER_OF_UNIQUE_JUMPS_FOUND = 43,
    TOTAL_NUMBER_OF_UNIQUE_JUMPS = 44,

    PASSENGERS_DROPPED_OFF_WITH_TAXI = 45,
    MONEY_MADE_WITH_TAXI = 46,

    MISSIONS_GIVEN = 47,
    MISSIONS_PASSED = 48,

    TOTAL_LEGITIMATE_KILLS = 49,
    LIVES_SAVED_WITH_AMBULANCE = 50,
    CRIMINALS_CAUGHT = 51,
    HIGHEST_LEVEL_AMBULANCE_MISSION = 52,
    HIGHEST_LEVEL_VIGILANTE_MISSION = 53,
    HIGHEST_LEVEL_FIRE_MISSION = 54,
    FIRES_EXTINGUISHED = 55,

    TOTAL_NUMBER_KILL_FRENZIES = 56,
    TOTAL_NUMBER_MISSIONS = 57,
    ROUNDS_FIRED_BY_PLAYER = 58,
    KGS_OF_EXPLOSIVES_USED = 59,
    BULLETS_THAT_HIT = 60,
    BEST_TIME_BOMB_DEFUSAL = 61,

    NUM_PROPERTY_OWNED = 62,
    PROPERTY_DESTROYED = 63,
    HIGHEST_CHASE_VALUE = 64,
    CHEATED_COUNT = 65,
    SHOW_CHASE_STAT_ON_SCREEN = 66,
    PAMPHLET_MISSION_PASSED = 67,

    BLOOD_RING_KILLS = 68,
    BLOOD_RING_TIME = 69,

    SPRAYINGS = 70,
    AUTO_PAINTING_BUDGET = 71,
    NO_MORE_HURRICANES = 72,
    FASHION_BUDGET = 73,
    PROPERTY_BUDGET = 74,
    WEAPON_BUDGET = 75,
    SAFE_HOUSE_VISITS = 76,
    TYRES_POPPED = 77,

    LONGEST_WHEELIE = 78,
    LONGEST_STOPPIE = 79,
    LONGEST_2_WHEEL = 80,
    LONGEST_WHEELIE_DIST = 81,
    LONGEST_STOPPIE_DIST = 82,
    LONGEST_2_WHEEL_DIST = 83,

	COUNT = 84
}


--------------
-- ReVC enums below
--------------
---
---


----------------
-- audio_enums.h
----------------
---


audio_enums.eRadioStation = {
	WILDSTYLE = 0,
	FLASH_FM = 1,
	KCHAT = 2,
	FEVER = 3,
	V_ROCK = 4,
	VCPR = 5,
	RADIO_ESPANTOSO = 6,
	EMOTION = 7,
	WAVE = 8,
	USERTRACK = 9,
	-- NUM_RADIOS = 10,
	-- POLICE_RADIO = 10,
	RADIO_OFF = 10,
	-- TAXI_RADIO,
}

audio_enums.eMusicMode = {
	MUSICMODE_FRONTEND = 0,
	MUSICMODE_GAME = 1,
	MUSICMODE_CUTSCENE = 2,
	MUSICMODE_DISABLE = 3,
	MUSICMODE_DISABLED = 4,
}

audio_enums.ePlayerMood = {
	PLAYER_MOOD_CALM = 0,
	PLAYER_MOOD_PISSED_OFF = 1,
	PLAYER_MOOD_ANGRY = 2,
	PLAYER_MOOD_WISECRACKING = 3,
	MAX_PLAYER_MOODS = 4,
}

audio_enums.eAudioType = {
	AUDIOTYPE_PHYSICAL = 0,
	AUDIOTYPE_EXPLOSION = 1,
	AUDIOTYPE_FIRE = 2,
	AUDIOTYPE_WEATHER = 3,
	AUDIOTYPE_SCRIPTOBJECT = 4,
-- GTA_BRIDGE
	-- AUDIOTYPE_BRIDGE,
-- GTA_BRIDGE
	AUDIOTYPE_COLLISION = 5,
	AUDIOTYPE_FRONTEND = 6,
	AUDIOTYPE_PROJECTILE = 7,
	AUDIOTYPE_GARAGE = 8,
	AUDIOTYPE_FIREHYDRANT = 9,
	AUDIOTYPE_WATERCANNON = 10,
	AUDIOTYPE_ESCALATOR = 11,
	AUDIOTYPE_EXTRA_SOUNDS = 12,
	AUDIOTYPE_POLICERADIO = 13,
	TOTAL_AUDIO_TYPES = 14,
}


----------------
-- EventList.h
----------------

event_enums.eEventType = {
	EVENT_NULL = 0,
	EVENT_ASSAULT = 1,
	EVENT_RUN_REDLIGHT = 2,
	EVENT_ASSAULT_POLICE = 3,
	EVENT_GUNSHOT = 4,
	EVENT_INJURED_PED = 5,
	EVENT_DEAD_PED = 6,
	EVENT_FIRE = 7,
	EVENT_STEAL_CAR = 8,
	EVENT_HIT_AND_RUN = 9,
	EVENT_HIT_AND_RUN_COP = 10,
	EVENT_SHOOT_PED = 11,
	EVENT_SHOOT_COP = 12,
	EVENT_EXPLOSION = 13,
	EVENT_PED_SET_ON_FIRE = 14,
	EVENT_COP_SET_ON_FIRE = 15,
	EVENT_CAR_SET_ON_FIRE = 16,
	EVENT_ASSAULT_NASTYWEAPON = 17,
	EVENT_ASSAULT_NASTYWEAPON_POLICE = 18,
	EVENT_UNK = 19,
	EVENT_ICECREAM = 20,
	EVENT_ATM = 21,
	EVENT_SHOPSTALL = 22,
	EVENT_SHOPWINDOW = 23,
	EVENT_LAST_EVENT = 24
}

event_enums.eEventEntity = {
	EVENT_ENTITY_NONE = 0,
	EVENT_ENTITY_PED = 1,
	EVENT_ENTITY_VEHICLE = 2,
	EVENT_ENTITY_OBJECT = 3
}

----------------
-- Font.h
----------------

-- Font type enums for drawing the fonts.
font_enums.eFontTypes = {
	FONT_BANK = 1,
	FONT_STANDARD = 2,
	FONT_HEADING = 3,
	FONT_JAPANESE = 4 -- Only enabled if 'MORE_LANGUAGES' is on in config.h, which it seems to be in my ReVC build.
	-- MAX_FONTS = FONT_HEADING
}

----------------
--- Camera.h
----------------

camera_enums.eFadeDirection = {
	-- Direction
	FADE_NONE = -1,
	FADE_OUT = 0,
	FADE_IN = 1
}

----------------
-- config.h
----------------

-- List of useful game limits from config.h, some have been modified
config_enums.eGameLimits = {
	NUMPLAYERS = 1,

	-- Well these can have the same numbers, I didn't think they could.
	MAX_CDIMAGES = 32, -- additional cdimages
	-- MAX_CDIMAGES2 = 32, -- additional cdimages
	MAX_CDCHANNELS = 5,

	NUMPHONES = 50
}


----------------
-- PlayerInfo.h
----------------

-- Game states for when the game is running.
-- These are set depending on what has happened with the player.
-- These are what run when the player is playing, wasted, and busted.
player_info_enums.eWastedBustedState = {
	WBSTATE_PLAYING = 0,
	WBSTATE_WASTED = 1,
	WBSTATE_BUSTED = 2,
	WBSTATE_FAILED_CRITICAL_MISSION = 3,
}

player_info_enums.eBustedAudioState = {
	BUSTEDAUDIO_NONE = 0,
	BUSTEDAUDIO_LOADING = 1,
	BUSTEDAUDIO_DONE = 2
}

----------------
-- WeaponType.h
----------------

-- local eWeaponType = {
weapon_enums.eWeaponType = {
	WEAPONTYPE_UNARMED = 0,
	WEAPONTYPE_BRASSKNUCKLE = 1,
	WEAPONTYPE_SCREWDRIVER = 2,
	WEAPONTYPE_GOLFCLUB = 3,
	WEAPONTYPE_NIGHTSTICK = 4,
	WEAPONTYPE_KNIFE = 5,
	WEAPONTYPE_BASEBALLBAT = 6,
	WEAPONTYPE_HAMMER = 7,
	WEAPONTYPE_CLEAVER = 8,
	WEAPONTYPE_MACHETE = 9,
	WEAPONTYPE_KATANA = 10,
	WEAPONTYPE_CHAINSAW = 11,
	WEAPONTYPE_GRENADE = 12,
	WEAPONTYPE_DETONATOR_GRENADE = 13,
	WEAPONTYPE_TEARGAS = 14,
	WEAPONTYPE_MOLOTOV = 15,
	WEAPONTYPE_ROCKET = 16,
	WEAPONTYPE_COLT45 = 17,
	WEAPONTYPE_PYTHON = 18,
	WEAPONTYPE_SHOTGUN = 19,
	WEAPONTYPE_SPAS12_SHOTGUN = 20,
	WEAPONTYPE_STUBBY_SHOTGUN = 21,
	WEAPONTYPE_TEC9 = 22,
	WEAPONTYPE_UZI = 23,
	WEAPONTYPE_SILENCED_INGRAM = 24,
	WEAPONTYPE_MP5 = 25,
	WEAPONTYPE_M4 = 26,
	WEAPONTYPE_RUGER = 27,
	WEAPONTYPE_SNIPERRIFLE = 28,
	WEAPONTYPE_LASERSCOPE = 29,
	WEAPONTYPE_ROCKETLAUNCHER = 30,
	WEAPONTYPE_FLAMETHROWER = 31,
	WEAPONTYPE_M60 = 32,
	WEAPONTYPE_MINIGUN = 33,
	WEAPONTYPE_DETONATOR = 34,
	WEAPONTYPE_HELICANNON = 35,
	WEAPONTYPE_CAMERA = 36,
	WEAPONTYPE_TOTALWEAPONS = 37,
	-- WEAPONTYPE_HEALTH = 37,
	-- WEAPONTYPE_ARMOUR = 38,
	-- WEAPONTYPE_RAMMEDBYCAR = 39,
	-- WEAPONTYPE_RUNOVERBYCAR = 40,
	-- WEAPONTYPE_EXPLOSION = 41,
	-- WEAPONTYPE_UZI_DRIVEBY = 42,
	-- WEAPONTYPE_DROWNING = 43,
	-- WEAPONTYPE_FALL = 44,
	-- WEAPONTYPE_UNIDENTIFIED = 45,
	-- WEAPONTYPE_ANYMELEE = 46,
	-- WEAPONTYPE_ANYWEAPON = 47
}

weapon_enums.eWeaponSlot = {
	WEAPONSLOT_UNARMED = 0,
	WEAPONSLOT_MELEE = 1,
	WEAPONSLOT_PROJECTILE = 2,
	WEAPONSLOT_HANDGUN = 3,
	WEAPONSLOT_SHOTGUN = 4,
	WEAPONSLOT_SUBMACHINEGUN = 5,
	WEAPONSLOT_RIFLE = 6,
	WEAPONSLOT_HEAVY = 7,
	WEAPONSLOT_SNIPER = 8,
	WEAPONSLOT_OTHER = 9,
	TOTAL_WEAPON_SLOTS = 10
}

weapon_enums.eWeaponFire = {
	WEAPON_FIRE_MELEE = 0,
	WEAPON_FIRE_INSTANT_HIT = 1,
	WEAPON_FIRE_PROJECTILE = 2,
	WEAPON_FIRE_AREA_EFFECT = 3,
	WEAPON_FIRE_CAMERA = 4
}

weapon_enums.eWeaponState = {
	WEAPONSTATE_READY = 0,
	WEAPONSTATE_FIRING = 1,
	WEAPONSTATE_RELOADING = 2,
	WEAPONSTATE_OUT_OF_AMMO = 3,
	WEAPONSTATE_MELEE_MADECONTACT = 4
};

----------------
-- ModelIndices.h
----------------

-- Weapon model indices, for loading the weapon model.

weapon_enums.eWeaponModelIndices = {
	MI_BRASS_KNUCKLES = 259,
	MI_SCREWDRIVER = 260,
	MI_GOLFCLUB = 261,
	MI_NIGHTSTICK = 262,
	MI_KNIFE = 263,
	MI_BASEBALL_BAT = 264,
	MI_HAMMER = 265,
	MI_MEAT_CLEAVER = 266,
	MI_MACHETE = 267,
	MI_KATANA = 268,
	MI_CHAINSAW = 269,
	MI_GRENADE = 270,
	MI_TEARGAS = 271,
	MI_MOLOTOV = 272,
	MI_MISSILE = 273,
	MI_COLT45 = 274,
	MI_PYTHON = 275,
	MI_RUGER = 276,
	MI_SHOTGUN = 277,
	MI_SPAS12_SHOTGUN = 278,
	MI_STUBBY_SHOTGUN = 279,
	MI_M4 = 280,
	MI_TEC9 = 281,
	MI_UZI = 282,
	MI_SILENCEDINGRAM = 283,
	MI_MP5 = 284,
	MI_SNIPERRIFLE = 285,
	MI_LASERSCOPE = 286,
	MI_ROCKETLAUNCHER = 287,
	MI_FLAMETHROWER = 288,
	MI_M60 = 289,
	MI_MINIGUN = 290,
	MI_BOMB = 291,
	MI_CAMERA = 292,
	MI_FINGERS = 293,
	MI_MINIGUN2 = 294,
}

----------------
-- Garages.h
----------------

garage_enums.eGarageState = {
	GS_FULLYCLOSED = 0,
	GS_OPENED = 1,
	GS_CLOSING = 2,
	GS_OPENING = 3,
	GS_OPENEDCONTAINSCAR = 4,
	GS_CLOSEDCONTAINSCAR = 5,
	GS_AFTERDROPOFF = 6,
}

garage_enums.eGarageType = {
	GARAGE_NONE = 0,
	GARAGE_MISSION = 1,
	GARAGE_BOMBSHOP1 = 2,
	GARAGE_BOMBSHOP2 = 3,
	GARAGE_BOMBSHOP3 = 4,
	GARAGE_RESPRAY = 5,
	GARAGE_COLLECTORSITEMS = 6,
	GARAGE_COLLECTSPECIFICCARS = 7,
	GARAGE_COLLECTCARS_1 = 8,
	GARAGE_COLLECTCARS_2 = 9,
	GARAGE_COLLECTCARS_3 = 10,
	GARAGE_FORCARTOCOMEOUTOF = 11,
	GARAGE_60SECONDS = 12,
	GARAGE_CRUSHER = 13,
	GARAGE_MISSION_KEEPCAR = 14,
	GARAGE_FOR_SCRIPT_TO_OPEN = 15,
	GARAGE_HIDEOUT_ONE = 16,
	GARAGE_HIDEOUT_TWO = 17,
	GARAGE_HIDEOUT_THREE = 18,
	GARAGE_FOR_SCRIPT_TO_OPEN_AND_CLOSE = 19,
	GARAGE_KEEPS_OPENING_FOR_SPECIFIC_CAR = 20,
	GARAGE_MISSION_KEEPCAR_REMAINCLOSED = 21,
	GARAGE_COLLECTCARS_4 = 22,
	GARAGE_FOR_SCRIPT_TO_OPEN_FOR_CAR = 23,
	GARAGE_HIDEOUT_FOUR = 24,
	GARAGE_HIDEOUT_FIVE = 25,
	GARAGE_HIDEOUT_SIX = 26,
	GARAGE_HIDEOUT_SEVEN = 27,
	GARAGE_HIDEOUT_EIGHT = 28,
	GARAGE_HIDEOUT_NINE = 29,
	GARAGE_HIDEOUT_TEN = 30,
	GARAGE_HIDEOUT_ELEVEN = 31,
	GARAGE_HIDEOUT_TWELVE = 32
}

-- The enums for each of these are set in the code.
-- garage_enums.eTotalGarageVariables = {
	-- TOTAL_COLLECTCARS_GARAGES = 4,
	-- TOTAL_HIDEOUT_GARAGES = 12,
	-- TOTAL_COLLECTCARS_CARS = 6
-- }

-- For stored car flags, mostly for the saves.
-- This can be used once I get my json save/load system working.
garage_enums.eStoredCarFlags = {
	FLAG_BULLETPROOF = 0x1,
	FLAG_FIREPROOF = 0x2,
	FLAG_EXPLOSIONPROOF = 0x4,
	FLAG_COLLISIONPROOF = 0x8,
	FLAG_MELEEPROOF = 0x10,
}

----------------
-- Radar.h
----------------
---


radar_enums.eBlipType = {
	BLIP_NONE,
	BLIP_CAR,
	BLIP_CHAR,
	BLIP_OBJECT,
	BLIP_COORD,
	BLIP_CONTACT_POINT
}

radar_enums.eBlipDisplay = {
	BLIP_DISPLAY_NEITHER = 0,
	BLIP_DISPLAY_MARKER_ONLY = 1,
	BLIP_DISPLAY_BLIP_ONLY = 2,
	BLIP_DISPLAY_BOTH = 3,
};

radar_enums.eRadarSprite = {
	RADAR_SPRITE_ENTITY_BLIP = -2,
	RADAR_SPRITE_COORD_BLIP = -1,
	RADAR_SPRITE_NONE = 0,
	RADAR_SPRITE_CENTRE = 1,
	RADAR_SPRITE_MAP_HERE = 2,
	RADAR_SPRITE_NORTH = 3,
	RADAR_SPRITE_AVERY = 4,
	RADAR_SPRITE_BIKER = 5,
	RADAR_SPRITE_CORTEZ = 6,
	RADAR_SPRITE_DIAZ = 7,
	RADAR_SPRITE_KENT = 8,
	RADAR_SPRITE_LAWYER = 9,
	RADAR_SPRITE_PHIL = 10,
	RADAR_SPRITE_BIKERS = 11,
	RADAR_SPRITE_BOATYARD = 12,
	RADAR_SPRITE_MALIBU_CLUB = 13,
	RADAR_SPRITE_CUBANS = 14,
	RADAR_SPRITE_FILM = 15,
	RADAR_SPRITE_GUN = 16,
	RADAR_SPRITE_HAITIANS = 17,
	RADAR_SPRITE_HARDWARE = 18,
	RADAR_SPRITE_SAVE = 19,
	RADAR_SPRITE_STRIP = 20,
	RADAR_SPRITE_ICE = 21,
	RADAR_SPRITE_KCABS = 22,
	RADAR_SPRITE_LOVEFIST = 23,
	RADAR_SPRITE_PRINTWORKS = 24,
	RADAR_SPRITE_PROPERTY = 25,
	RADAR_SPRITE_SUNYARD = 26,
	RADAR_SPRITE_SPRAY = 27,
	RADAR_SPRITE_TSHIRT = 28,
	RADAR_SPRITE_TOMMY = 29,
	RADAR_SPRITE_PHONE = 30,
	RADAR_SPRITE_RADIO_WILDSTYLE = 31,
	RADAR_SPRITE_RADIO_FLASH = 32,
	RADAR_SPRITE_RADIO_KCHAT = 33,
	RADAR_SPRITE_RADIO_FEVER = 34,
	RADAR_SPRITE_RADIO_VROCK = 35,
	RADAR_SPRITE_RADIO_VCPR = 36,
	RADAR_SPRITE_RADIO_ESPANTOSO = 37,
	RADAR_SPRITE_RADIO_EMOTION = 38,
	RADAR_SPRITE_RADIO_WAVE = 39,
-- MAP_ENHANCEMENTS
	RADAR_SPRITE_WAYPOINT = 40,
-- MAP_ENHANCEMENTS

	RADAR_SPRITE_COUNT = 41
}

radar_enums.eRadarTraces = {
	RADAR_TRACE_RED = 0,
	RADAR_TRACE_GREEN = 1,
	RADAR_TRACE_LIGHT_BLUE = 2,
	RADAR_TRACE_GRAY = 3,
	RADAR_TRACE_YELLOW = 4,
	RADAR_TRACE_MAGENTA = 5,
	RADAR_TRACE_CYAN = 6
}


radar_enums.eRadarModes = {
	BLIP_MODE_TRIANGULAR_UP = 0,
	BLIP_MODE_TRIANGULAR_DOWN,
	BLIP_MODE_SQUARE,
}


----------------
--- Weather.h
----------------

weather_enums.eWeatherType = {
	-- WEATHER_RANDOM = -1,
	WEATHER_SUNNY = 0,
	WEATHER_CLOUDY = 1,
	WEATHER_RAINY = 2,
	WEATHER_FOGGY = 3,
	WEATHER_EXTRA_SUNNY = 4,
	WEATHER_HURRICANE = 5,
	WEATHER_TOTAL = 6,

	-- WEATHER_EXTRACOLOURS = 6
}



----------------
-- PedType.h
----------------

-- enum ePedType
-- {
-- 	PEDTYPE_PLAYER1,
-- 	PEDTYPE_PLAYER2,
-- 	PEDTYPE_PLAYER3,
-- 	PEDTYPE_PLAYER4,
-- 	PEDTYPE_CIVMALE,
-- 	PEDTYPE_CIVFEMALE,
-- 	PEDTYPE_COP,
-- 	PEDTYPE_GANG1,
-- 	PEDTYPE_GANG2,
-- 	PEDTYPE_GANG3,
-- 	PEDTYPE_GANG4,
-- 	PEDTYPE_GANG5, -- Security - hardcoded
-- 	PEDTYPE_GANG6,
-- 	PEDTYPE_GANG7, -- Vercetti gang - hardcoded
-- 	PEDTYPE_GANG8,
-- 	PEDTYPE_GANG9,
-- 	PEDTYPE_EMERGENCY,
-- 	PEDTYPE_FIREMAN,
-- 	PEDTYPE_CRIMINAL,
-- 	PEDTYPE_UNUSED1,
-- 	PEDTYPE_PROSTITUTE,
-- 	PEDTYPE_SPECIAL,
-- 	PEDTYPE_UNUSED2,

-- 	NUM_PEDTYPES
-- };


----------------
-- Ped.h
----------------

-- PedState

	-- PED_NONE,
	-- PED_IDLE,
	-- PED_LOOK_ENTITY,
	-- PED_LOOK_HEADING,
	-- PED_WANDER_RANGE,
	-- PED_WANDER_PATH,
	-- PED_SEEK_POS,
	-- PED_SEEK_ENTITY,
	-- PED_FLEE_POS,
	-- PED_FLEE_ENTITY,
	-- PED_PURSUE,
	-- PED_FOLLOW_PATH,
	-- PED_SNIPER_MODE,
	-- PED_ROCKET_MODE,
	-- PED_DUMMY,
	-- PED_PAUSE,
	-- PED_ATTACK,
	-- PED_FIGHT,
	-- PED_FACE_PHONE,
	-- PED_MAKE_CALL,
	-- PED_CHAT,
	-- PED_MUG,
	-- PED_AIM_GUN,
	-- PED_AI_CONTROL,
	-- PED_SEEK_CAR,
	-- PED_SEEK_IN_BOAT,
	-- PED_FOLLOW_ROUTE,
	-- PED_CPR,
	-- PED_SOLICIT,
	-- PED_BUY_ICECREAM,
	-- PED_INVESTIGATE,
	-- PED_STEP_AWAY,
	-- PED_ON_FIRE,
	-- PED_SUN_BATHE,
	-- PED_FLASH,
	-- PED_JOG,
	-- PED_ANSWER_MOBILE,

	-- PED_UNKNOWN,

	-- PED_STATES_NO_AI,

	-- PED_ABSEIL,
	-- PED_SIT,
	-- PED_JUMP,
	-- PED_FALL,
	-- PED_GETUP,
	-- PED_STAGGER,
	-- PED_DIVE_AWAY,

	-- PED_STATES_NO_ST,
	-- PED_ENTER_TRAIN,
	-- PED_EXIT_TRAIN,
	-- PED_ARREST_PLAYER,

	-- PED_DRIVING,
	-- PED_PASSENGER,
	-- PED_TAXI_PASSENGER,
	-- PED_OPEN_DOOR,
	-- PED_DIE,
	-- PED_DEAD,
	-- PED_CARJACK,
	-- PED_DRAG_FROM_CAR,
	-- PED_ENTER_CAR,
	-- PED_STEAL_CAR,
	-- PED_EXIT_CAR,
	-- PED_HANDS_UP,
	-- PED_ARRESTED,
	-- PED_DEPLOY_STINGER

-- eMoveState
	-- PEDMOVE_NONE,
	-- PEDMOVE_STILL,
	-- PEDMOVE_WALK,
	-- PEDMOVE_JOG,
	-- PEDMOVE_RUN,
	-- PEDMOVE_SPRINT,
	-- PEDMOVE_THROWN

-- eWaitState
	-- WAITSTATE_FALSE,
	-- WAITSTATE_TRAFFIC_LIGHTS,
	-- WAITSTATE_CROSS_ROAD,
	-- WAITSTATE_CROSS_ROAD_LOOK,
	-- WAITSTATE_LOOK_PED,
	-- WAITSTATE_LOOK_SHOP,
	-- WAITSTATE_LOOK_ACCIDENT,
	-- WAITSTATE_FACEOFF_GANG,
	-- WAITSTATE_DOUBLEBACK,
	-- WAITSTATE_HITWALL,
	-- WAITSTATE_TURN180,
	-- WAITSTATE_SURPRISE,
	-- WAITSTATE_STUCK,
	-- WAITSTATE_LOOK_ABOUT,
	-- WAITSTATE_PLAYANIM_DUCK,
	-- WAITSTATE_PLAYANIM_COWER,
	-- WAITSTATE_PLAYANIM_TAXI,
	-- WAITSTATE_PLAYANIM_HANDSUP,
	-- WAITSTATE_PLAYANIM_HANDSCOWER,
	-- WAITSTATE_PLAYANIM_CHAT,
	-- WAITSTATE_FINISH_FLEE,
	-- WAITSTATE_SIT_DOWN,
	-- WAITSTATE_SIT_DOWN_RVRS,
	-- WAITSTATE_SIT_UP,
	-- WAITSTATE_SIT_IDLE,
	-- WAITSTATE_USE_ATM,
	-- WAITSTATE_SUN_BATHE_PRE,
	-- WAITSTATE_SUN_BATHE_DOWN,
	-- WAITSTATE_SUN_BATHE_IDLE,
	-- WAITSTATE_RIOT,
	-- WAITSTATE_FAST_FALL,
	-- WAITSTATE_BOMBER,
	-- WAITSTATE_STRIPPER,
	-- WAITSTATE_GROUND_ATTACK,
	-- WAITSTATE_LANCESITTING,
	-- WAITSTATE_PLAYANIM_HANDSUP_SIMPLE,

-- eObjective

    -- "OBJECTIVE_NONE"
	-- OBJECTIVE_WAIT_ON_FOOT,
	-- OBJECTIVE_WAIT_ON_FOOT_FOR_COP,
	-- OBJECTIVE_FLEE_ON_FOOT_TILL_SAFE,
	-- OBJECTIVE_GUARD_SPOT,
	-- OBJECTIVE_GUARD_AREA,
	-- OBJECTIVE_WAIT_IN_CAR,
	-- OBJECTIVE_WAIT_IN_CAR_THEN_GET_OUT,
	-- OBJECTIVE_KILL_CHAR_ON_FOOT,
	-- OBJECTIVE_KILL_CHAR_ANY_MEANS,
	-- OBJECTIVE_FLEE_CHAR_ON_FOOT_TILL_SAFE,
	-- OBJECTIVE_FLEE_CHAR_ON_FOOT_ALWAYS,
	-- OBJECTIVE_GOTO_CHAR_ON_FOOT,
	-- OBJECTIVE_GOTO_CHAR_ON_FOOT_WALKING,
	-- OBJECTIVE_HASSLE_CHAR,
	-- OBJECTIVE_FOLLOW_CHAR_IN_FORMATION,
	-- OBJECTIVE_LEAVE_CAR,
	-- OBJECTIVE_ENTER_CAR_AS_PASSENGER,
	-- OBJECTIVE_ENTER_CAR_AS_DRIVER,
	-- OBJECTIVE_FOLLOW_CAR_IN_CAR,
	-- OBJECTIVE_FIRE_AT_OBJECT_FROM_VEHICLE,
	-- OBJECTIVE_DESTROY_OBJECT,
	-- OBJECTIVE_DESTROY_CAR,
	-- OBJECTIVE_GOTO_AREA_ANY_MEANS,
	-- OBJECTIVE_GOTO_AREA_ON_FOOT,
	-- OBJECTIVE_RUN_TO_AREA,
	-- OBJECTIVE_GOTO_AREA_IN_CAR,
	-- OBJECTIVE_FOLLOW_CAR_ON_FOOT_WITH_OFFSET,
	-- OBJECTIVE_GUARD_ATTACK,
	-- OBJECTIVE_SET_LEADER,
	-- OBJECTIVE_FOLLOW_ROUTE,
	-- OBJECTIVE_SOLICIT_VEHICLE,
	-- OBJECTIVE_HAIL_TAXI,
	-- OBJECTIVE_CATCH_TRAIN,
	-- OBJECTIVE_BUY_ICE_CREAM,
	-- OBJECTIVE_STEAL_ANY_CAR,
	-- OBJECTIVE_STEAL_ANY_MISSION_CAR,
	-- OBJECTIVE_MUG_CHAR,
	-- OBJECTIVE_LEAVE_CAR_AND_DIE,
	-- OBJECTIVE_GOTO_SEAT_ON_FOOT,
	-- OBJECTIVE_GOTO_ATM_ON_FOOT,
	-- OBJECTIVE_FLEE_CAR,
	-- OBJECTIVE_SUN_BATHE,
	-- OBJECTIVE_GOTO_BUS_STOP_ON_FOOT,
	-- OBJECTIVE_GOTO_PIZZA_ON_FOOT,
	-- OBJECTIVE_GOTO_SHELTER_ON_FOOT,
	-- OBJECTIVE_AIM_GUN_AT,
	-- OBJECTIVE_WANDER,
	-- OBJECTIVE_WAIT_ON_FOOT_AT_SHELTER,
	-- OBJECTIVE_SPRINT_TO_AREA,
	-- OBJECTIVE_KILL_CHAR_ON_BOAT,
	-- OBJECTIVE_SOLICIT_FOOT,
	-- OBJECTIVE_WAIT_ON_FOOT_AT_BUS_STOP,
	-- OBJECTIVE_GOTO_ICE_CREAM_VAN_ON_FOOT,
	-- OBJECTIVE_WAIT_ON_FOOT_AT_ICE_CREAM_VAN,
	-- OBJ_55,
	-- OBJ_56,
	-- OBJ_57,
	-- OBJ_58,
	-- OBJ_59
