-- SPDX-License-Identifier: MIT
-- Copyright (c) 2026 kelson8

-- List of enums for future use in my Lua scripts.

-- Source - https://stackoverflow.com/a/77170992
-- Posted by Maldus
-- Retrieved 2026-09-06, License - CC BY-SA 4.0

-- Testing with an enum in lua.

local enum = function(keys)
    local Enum = {}
    for _, value in ipairs(keys) do
        Enum[value] = {}
    end
    return Enum
end

local Result = enum { "Success", "Failure" }

-- Tables to be read from other files.

audio_enums = {}

camera_enums = {}

config_enums = {}

event_enums = {}

game_enums = {}

font_enums = {}

garage_enums = {}

stat_enums = {}

radar_enums = {}

weapon_enums = {}

weather_enums = {}

world_enums = {}

zone_enums = {}

-- clothes_enums = {}

pickup_enums = {}

player_enums = {}
player_info_enums = {}


ped_enums = {}

-- vehicle_enums = {}

--------------
--- Custom enums below
--------------
---

custom_save = {}

-- These should match what is set in the games code.
-- If this is changed, loading/saving might not work.
custom_save.eSaveVersion = {
	save_format = "revc-freeroam",
	save_version = 1
}

-- misc_enums.h
--------------
---

--- The types for the stats.
--- Mostly used for my lua scripts.
stat_enums.eStatType = {
    SEAGULLS_KILLED = 0,
    DAYS_PASSED = 1,
    HEADS_POPPED = 2,
    COMMERCIAL_PASSED = 3,
    INDUSTRIAL_PASSED = 4,
    SUBURBAN_PASSED = 5,
    NUMBER_KILL_FRENZIES_PASSED = 6,
    PEOPLE_KILLED_BY_OTHERS = 7,
    HELIS_DESTROYED = 8,
    TIMES_DIED = 9,
    TIMES_ARRESTED = 10,
    KILLS_SINCE_LAST_CHECKPOINT = 11,

    DISTANCE_TRAVELLED_BY_CAR = 12,
    DISTANCE_TRAVELLED_BY_HELICOPTOR = 13,
    DISTANCE_TRAVELLED_BY_BIKE = 14,
    DISTANCE_TRAVELLED_BY_BOAT = 15,
    DISTANCE_TRAVELLED_BY_PLANE = 16,
    DISTANCE_TRAVELLED_BY_GOLF_CART = 17,
    DISTANCE_TRAVELLED_ON_FOOT = 18,

    FLIGHT_TIME = 19,
    TIMES_DROWNED = 20,
    PHOTOS_TAKEN = 21,

    LOAN_SHARKS = 22,
    STORES_KNOCKED_OFF = 23,
    MOVIE_STUNTS = 24,
    ASSASSINATIONS = 25,
    PIZZAS_DELIVERED = 26,
    GARBAGE_PICKUPS = 27,
    ICE_CREAM_SOLD = 28,
    TOP_SHOOTING_RANGE_SCORE = 29,
    SHOOTING_RANK = 30,

    CARS_EXPLODED = 31,
    BOATS_EXPLODED = 32,
    WANTED_STARS_ATTAINED = 33,
    WANTED_STARS_EVADED = 34,
    PEOPLE_KILLED_BY_PLAYER = 35,

    PROGRESS_MADE = 36,
    TOTAL_PROGRESS_IN_GAME = 37,
    MAXIMUM_JUMP_DISTANCE = 38,
    MAXIMUM_JUMP_HEIGHT = 39,
    MAXIMUM_JUMP_FLIPS = 40,
    MAXIMUM_JUMP_SPINS = 41,
    BEST_STUNT_JUMP = 42,
    NUMBER_OF_UNIQUE_JUMPS_FOUND = 43,
    TOTAL_NUMBER_OF_UNIQUE_JUMPS = 44,

    PASSENGERS_DROPPED_OFF_WITH_TAXI = 45,
    MONEY_MADE_WITH_TAXI = 46,

    MISSIONS_GIVEN = 47,
    MISSIONS_PASSED = 48,

    TOTAL_LEGITIMATE_KILLS = 49,
    LIVES_SAVED_WITH_AMBULANCE = 50,
    CRIMINALS_CAUGHT = 51,
    HIGHEST_LEVEL_AMBULANCE_MISSION = 52,
    HIGHEST_LEVEL_VIGILANTE_MISSION = 53,
    HIGHEST_LEVEL_FIRE_MISSION = 54,
    FIRES_EXTINGUISHED = 55,

    TOTAL_NUMBER_KILL_FRENZIES = 56,
    TOTAL_NUMBER_MISSIONS = 57,
    ROUNDS_FIRED_BY_PLAYER = 58,
    KGS_OF_EXPLOSIVES_USED = 59,
    BULLETS_THAT_HIT = 60,
    BEST_TIME_BOMB_DEFUSAL = 61,

    NUM_PROPERTY_OWNED = 62,
    PROPERTY_DESTROYED = 63,
    HIGHEST_CHASE_VALUE = 64,
    CHEATED_COUNT = 65,
    SHOW_CHASE_STAT_ON_SCREEN = 66,
    PAMPHLET_MISSION_PASSED = 67,

    BLOOD_RING_KILLS = 68,
    BLOOD_RING_TIME = 69,

    SPRAYINGS = 70,
    AUTO_PAINTING_BUDGET = 71,
    NO_MORE_HURRICANES = 72,
    FASHION_BUDGET = 73,
    PROPERTY_BUDGET = 74,
    WEAPON_BUDGET = 75,
    SAFE_HOUSE_VISITS = 76,
    TYRES_POPPED = 77,

    LONGEST_WHEELIE = 78,
    LONGEST_STOPPIE = 79,
    LONGEST_2_WHEEL = 80,
    LONGEST_WHEELIE_DIST = 81,
    LONGEST_STOPPIE_DIST = 82,
    LONGEST_2_WHEEL_DIST = 83,

	COUNT = 84
}


--------------
-- ReVC enums below
--------------
---
---


----------------
-- audio_enums.h
----------------
---


audio_enums.eRadioStation = {
	WILDSTYLE = 0,
	FLASH_FM = 1,
	KCHAT = 2,
	FEVER = 3,
	V_ROCK = 4,
	VCPR = 5,
	RADIO_ESPANTOSO = 6,
	EMOTION = 7,
	WAVE = 8,
	USERTRACK = 9,
	-- NUM_RADIOS = 10,
	-- POLICE_RADIO = 10,
	RADIO_OFF = 10,
	-- TAXI_RADIO,
}

audio_enums.eMusicMode = {
	MUSICMODE_FRONTEND = 0,
	MUSICMODE_GAME = 1,
	MUSICMODE_CUTSCENE = 2,
	MUSICMODE_DISABLE = 3,
	MUSICMODE_DISABLED = 4,
}

audio_enums.ePlayerMood = {
	PLAYER_MOOD_CALM = 0,
	PLAYER_MOOD_PISSED_OFF = 1,
	PLAYER_MOOD_ANGRY = 2,
	PLAYER_MOOD_WISECRACKING = 3,
	MAX_PLAYER_MOODS = 4,
}

audio_enums.eAudioType = {
	AUDIOTYPE_PHYSICAL = 0,
	AUDIOTYPE_EXPLOSION = 1,
	AUDIOTYPE_FIRE = 2,
	AUDIOTYPE_WEATHER = 3,
	AUDIOTYPE_SCRIPTOBJECT = 4,
-- GTA_BRIDGE
	-- AUDIOTYPE_BRIDGE,
-- GTA_BRIDGE
	AUDIOTYPE_COLLISION = 5,
	AUDIOTYPE_FRONTEND = 6,
	AUDIOTYPE_PROJECTILE = 7,
	AUDIOTYPE_GARAGE = 8,
	AUDIOTYPE_FIREHYDRANT = 9,
	AUDIOTYPE_WATERCANNON = 10,
	AUDIOTYPE_ESCALATOR = 11,
	AUDIOTYPE_EXTRA_SOUNDS = 12,
	AUDIOTYPE_POLICERADIO = 13,
	TOTAL_AUDIO_TYPES = 14,
}

---
-- Sound effect types
---

audio_enums.eSound = {
	SOUND_CAR_DOOR_CLOSE_BONNET = 0,
	SOUND_CAR_DOOR_CLOSE_BUMPER = 1,
	SOUND_CAR_DOOR_CLOSE_FRONT_LEFT = 2,
	SOUND_CAR_DOOR_CLOSE_FRONT_RIGHT = 3,
	SOUND_CAR_DOOR_CLOSE_BACK_LEFT = 4,
	SOUND_CAR_DOOR_CLOSE_BACK_RIGHT = 5,
	SOUND_CAR_DOOR_OPEN_BONNET = 6,
	SOUND_CAR_DOOR_OPEN_BUMPER = 7,
	SOUND_CAR_DOOR_OPEN_FRONT_LEFT = 8,
	SOUND_CAR_DOOR_OPEN_FRONT_RIGHT = 9,
	SOUND_CAR_DOOR_OPEN_BACK_LEFT = 10,

	SOUND_CAR_DOOR_OPEN_BACK_RIGHT = 11,
	SOUND_CAR_WINDSHIELD_CRACK = 12,
	SOUND_CAR_JUMP = 13,
	SOUND_CAR_JUMP_2 = 14,
	SOUND_CAR_TYRE_POP = 15,
	SOUND_16 = 16,
	SOUND_17 = 17,
	SOUND_CAR_ENGINE_START = 18,
	SOUND_CAR_LIGHT_BREAK = 19,
	SOUND_CAR_HYDRAULIC_1 = 20,

	SOUND_CAR_HYDRAULIC_2 = 21,
	SOUND_CAR_HYDRAULIC_3 = 21,
	SOUND_CAR_JERK = 23,
	SOUND_CAR_SPLASH = 24,
	SOUND_BOAT_SLOWDOWN = 25,
	SOUND_TRAIN_DOOR_CLOSE = 26,
	SOUND_TRAIN_DOOR_OPEN = 27,
	SOUND_CAR_TANK_TURRET_ROTATE = 28,
	SOUND_CAR_BOMB_TICK = 29,

	SOUND_PLANE_ON_GROUND = 30,
	SOUND_HELI_BLADE = 31,
	SOUND_32 = 32,
	SOUND_STEP_START = 33,
	SOUND_STEP_END = 34,
	SOUND_FALL_LAND = 35,
	SOUND_FALL_COLLAPSE = 36,
	SOUND_FIGHT_37 = 37,
	SOUND_FIGHT_38 = 38,
	SOUND_FIGHT_39 = 39,

	SOUND_FIGHT_40 = 40,
	SOUND_FIGHT_41 = 41,
	SOUND_FIGHT_42 = 42,
	SOUND_FIGHT_43 = 43,
	SOUND_FIGHT_44 = 44,
	SOUND_FIGHT_45 = 45,
	SOUND_FIGHT_46 = 46,
	SOUND_FIGHT_47 = 47,
	SOUND_FIGHT_48 = 48,
	SOUND_49 = 49,

	SOUND_WEAPON_BAT_ATTACK = 50,
	SOUND_WEAPON_KNIFE_ATTACK = 51,
	SOUND_WEAPON_CHAINSAW_IDLE = 52,
	SOUND_WEAPON_CHAINSAW_ATTACK = 53,
	SOUND_WEAPON_CHAINSAW_MADECONTACT = 54,
	SOUND_WEAPON_SHOT_FIRED = 55,
	SOUND_WEAPON_RELOAD = 56,
	SOUND_WEAPON_AK47_BULLET_ECHO = 57,
	SOUND_WEAPON_FLAMETHROWER_FIRE = 58,
	SOUND_WEAPON_SNIPER_SHOT_NO_ZOOM = 59,
	SOUND_WEAPON_ROCKET_SHOT_NO_ZOOM = 60,

	SOUND_WEAPON_HIT_PED = 61,
	SOUND_WEAPON_HIT_VEHICLE = 62,
	SOUND_GARAGE_NO_MONEY = 63,
	SOUND_GARAGE_BAD_VEHICLE = 64,
	SOUND_GARAGE_OPENING = 65,
	SOUND_GARAGE_BOMB_ALREADY_SET = 66,
	SOUND_GARAGE_BOMB1_SET = 67,
	SOUND_GARAGE_BOMB2_SET = 68,
	SOUND_GARAGE_BOMB3_SET = 69,

	SOUND_70 = 70,
	SOUND_71 = 71,
	SOUND_GARAGE_VEHICLE_DECLINED = 72,
	SOUND_GARAGE_VEHICLE_ACCEPTED = 73,
	SOUND_GARAGE_DOOR_CLOSED = 74,
	SOUND_GARAGE_DOOR_OPENED = 75,
	SOUND_CRANE_PICKUP = 76,
	SOUND_PICKUP_WEAPON_BOUGHT = 77,
	SOUND_PICKUP_WEAPON = 78,
	SOUND_PICKUP_HEALTH = 79,

	SOUND_80 = 80,
	SOUND_81 = 81,
	SOUND_PICKUP_ADRENALINE = 82,
	SOUND_PICKUP_ARMOUR = 83,
	SOUND_PICKUP_BONUS = 84,
	SOUND_PICKUP_MONEY = 85,
	SOUND_PICKUP_HIDDEN_PACKAGE = 86,
	SOUND_PICKUP_PACMAN_PILL = 87,
	SOUND_PICKUP_PACMAN_PACKAGE = 88,
	SOUND_PICKUP_FLOAT_PACKAGE = 89,

	SOUND_BOMB_TIMED_ACTIVATED = 90,
	SOUND_91 = 91,
	SOUND_BOMB_ONIGNITION_ACTIVATED = 92,
	SOUND_BOMB_TICK = 93,
	SOUND_RAMPAGE_START = 94,
	SOUND_RAMPAGE_ONGOING = 95,
	SOUND_RAMPAGE_PASSED = 96,
	SOUND_RAMPAGE_FAILED = 97,
	SOUND_RAMPAGE_KILL = 98,
	SOUND_RAMPAGE_CAR_BLOWN = 99,

	SOUND_EVIDENCE_PICKUP = 100,
	SOUND_UNLOAD_GOLD = 101,
	SOUND_PAGER = 102,
	SOUND_PED_DEATH = 103,
	SOUND_PED_DAMAGE = 104,
	SOUND_PED_HIT = 105,
	SOUND_PED_LAND = 106,
	SOUND_PED_BULLET_HIT = 107,
	SOUND_PED_BURNING = 108,
	SOUND_PED_PLAYER_REACTTOCOP = 109,

	SOUND_PED_ARREST_COP = 110,
	SOUND_PED_MIAMIVICE_EXITING_CAR = 111,
	SOUND_PED_COP_HELIPILOTPHRASE = 112,
	SOUND_PED_PULLOUTWEAPON = 113,
	SOUND_PED_HELI_PLAYER_FOUND = 114,
	SOUND_PED_VCPA_PLAYER_FOUND = 115,
	SOUND_PED_ON_FIRE = 116,
	SOUND_PED_AIMING = 117,
	SOUND_PED_HANDS_UP = 118,
	SOUND_PED_HANDS_COWER = 119,

	SOUND_PED_FLEE_SPRINT = 120,
	SOUND_PED_CAR_JACKINGT = 121,
	SOUND_PED_MUGGINGT = 122,
	SOUND_PED_CAR_JACKEDT = 123,
	SOUND_PED_ROBBEDT = 124,
	SOUND_PED_ACCIDENTREACTION1T = 125,
	SOUND_PED_INNOCENTT = 126,

	SOUND_PED_PLAYER_AFTERSEXT = 127,
	SOUND_PED_PLAYER_BEFORESEXT = 128,
	SOUND_PED_COP_TARGETINGT = 129, --  also used for medics


	SOUND_PED_COP_MANYCOPSAROUNDT = 130, -- also used for medics
	SOUND_PED_GUNAIMEDAT2 = 131,
	SOUND_PED_COP_ALONE = 132, -- also used for medics
	SOUND_PED_GUNAIMEDAT3 = 133,
	SOUND_PED_COP_ASK_FOR_ID = 134,
	SOUND_PED_COP_LITTLECOPSAROUND = 135, -- also used for medics
	SOUND_PED_PLAYER_FARFROMCOPS = 136, -- also used for medics
	SOUND_PED_TAXI_WAIT = 137,
	SOUND_PED_ATTACK = 138,
	SOUND_PED_DEFEND = 139,

	SOUND_PED_HEALING = 140,
	SOUND_PED_LEAVE_VEHICLE = 141,
	SOUND_PED_EVADE = 142,
	SOUND_PED_FLEE_RUN = 143,
	SOUND_PED_CRASH_VEHICLE = 144,
	SOUND_PED_CRASH_CAR = 145,
	SOUND_PED_ANNOYED_DRIVER = 146,
	SOUND_PED_147 = 147,
	SOUND_PED_SOLICIT = 148,
	SOUND_PED_JEER = 149,

	SOUND_PED_150 = 150,
	SOUND_PED_EXTINGUISHING_FIRE = 151,
	SOUND_PED_WAIT_DOUBLEBACK = 152,
	SOUND_PED_CHAT_SEXY_FEMALE = 153,

	SOUND_PED_CHAT_SEXY_MALE = 154,
	SOUND_PED_CHAT_EVENT = 155,
	SOUND_PED_PED_COLLISION = 156,
	SOUND_PED_CHAT = 157,
	SOUND_PED_TAXI_CALL = 158,
	SOUND_RACE_START_3 = 159,

	SOUND_RACE_START_2 = 160,
	SOUND_RACE_START_1 = 161,
	SOUND_RACE_START_GO = 162,
	SOUND_SPLASH = 163,
	SOUND_WATER_FALL = 164,
	SOUND_SPLATTER = 165,
	SOUND_CAR_PED_COLLISION = 166,
	SOUND_CLOCK_TICK = 167,
	SOUND_PART_MISSION_COMPLETE = 168,
	SOUND_FRONTEND_MENU_STARTING = 169, -- same sound as SOUND_HUD

	-- 170-175 are invalid.

	SOUND_FRONTEND_RADIO_TURN_OFF = 176, -- those 2 are same sound
	SOUND_FRONTEND_RADIO_TURN_ON = 177,
	SOUND_FRONTEND_HURRICANE = 178,
	SOUND_HUD = 179,

	SOUND_180 = 180,
	SOUND_181 = 181,
	SOUND_182 = 182,
	SOUND_LIGHTNING = 183,
	SOUND_BULLETTRACE_1 = 184,
	SOUND_BULLETTRACE_2 = 185,
	SOUND_186 = 186, -- makes same sound as 40
	SOUND_187 = 187, -- makes same sound as 46
	SOUND_MELEE_ATTACK_START = 188,
	SOUND_SKATING = 189,

	SOUND_WEAPON_MINIGUN_ATTACK = 190,
	SOUND_WEAPON_MINIGUN_2 = 191,
	SOUND_WEAPON_MINIGUN_3 = 192,
	SOUND_AMMUNATION_IMRAN_ARM_BOMB = 193,
	SOUND_RADIO_CHANGE = 194,
	SOUND_FRONTEND_HIGHLIGHT_OPTION = 195,
	SOUND_FRONTEND_ENTER_OR_ADJUST = 196,
	SOUND_FRONTEND_BACK = 197,
	SOUND_FRONTEND_FAIL = 198,
	SOUND_FRONTEND_AUDIO_TEST = 199,

	SOUND_INJURED_PED_MALE_OUCH = 200,
	SOUND_INJURED_PED_FEMALE = 201,
	SOUND_SHIRT_WIND_FLAP = 202,
	SOUND_SET_203 = 203,
	SOUND_TOTAL_SOUNDS = 204,
	SOUND_NO_SOUND = 205,
}


----------------
--- Camera.h
----------------

camera_enums.eFadeDirection = {
	-- Direction
	FADE_NONE = -1,
	FADE_OUT = 0,
	FADE_IN = 1
}

----------------
-- config.h
----------------

-- List of useful game limits from config.h, some have been modified
-- These should be kept in sync with my internal ReVC branch, otherwise things may break.
config_enums.eGameLimits = {
	NUMPLAYERS = 1,

	-- Well these can have the same numbers, I didn't think they could.
	MAX_CDIMAGES = 32, -- additional cdimages
	-- MAX_CDIMAGES2 = 32, -- additional cdimages
	MAX_CDCHANNELS = 5,

	NUMPHONES = 50,

	-- The max amount of garages, my scripts should check for this if I'm creating them.
	NUM_GARAGES = 32
}


----------------
-- EventList.h
----------------

event_enums.eEventType = {
	EVENT_NULL = 0,
	EVENT_ASSAULT = 1,
	EVENT_RUN_REDLIGHT = 2,
	EVENT_ASSAULT_POLICE = 3,
	EVENT_GUNSHOT = 4,
	EVENT_INJURED_PED = 5,
	EVENT_DEAD_PED = 6,
	EVENT_FIRE = 7,
	EVENT_STEAL_CAR = 8,
	EVENT_HIT_AND_RUN = 9,
	EVENT_HIT_AND_RUN_COP = 10,
	EVENT_SHOOT_PED = 11,
	EVENT_SHOOT_COP = 12,
	EVENT_EXPLOSION = 13,
	EVENT_PED_SET_ON_FIRE = 14,
	EVENT_COP_SET_ON_FIRE = 15,
	EVENT_CAR_SET_ON_FIRE = 16,
	EVENT_ASSAULT_NASTYWEAPON = 17,
	EVENT_ASSAULT_NASTYWEAPON_POLICE = 18,
	EVENT_UNK = 19,
	EVENT_ICECREAM = 20,
	EVENT_ATM = 21,
	EVENT_SHOPSTALL = 22,
	EVENT_SHOPWINDOW = 23,
	EVENT_LAST_EVENT = 24
}

event_enums.eEventEntity = {
	EVENT_ENTITY_NONE = 0,
	EVENT_ENTITY_PED = 1,
	EVENT_ENTITY_VEHICLE = 2,
	EVENT_ENTITY_OBJECT = 3
}

----------------
-- Font.h
----------------

-- Font type enums for drawing the fonts.
font_enums.eFontTypes = {
	FONT_BANK = 1,
	FONT_STANDARD = 2,
	FONT_HEADING = 3,
	FONT_JAPANESE = 4 -- Only enabled if 'MORE_LANGUAGES' is on in config.h, which it seems to be in my ReVC build.
	-- MAX_FONTS = FONT_HEADING
}

----------------
-- Game.h
----------------


game_enums.eLevelName = {
	-- LEVEL_IGNORE = -1,
	LEVEL_GENERIC = 0,
	LEVEL_BEACH = 1,
	LEVEL_MAINLAND = 2,

	-- NUM_LEVELS
}

game_enums.eAreaName = {
	AREA_MAIN_MAP = 0,
	AREA_HOTEL = 1,
	AREA_MANSION = 2,
	AREA_BANK = 3,
	AREA_MALL = 4,
	AREA_STRIP_CLUB = 5,
	AREA_LAWYERS = 6,
	AREA_COFFEE_SHOP = 7,
	AREA_CONCERT_HALL = 8,
	AREA_STUDIO = 9,
	AREA_RIFLE_RANGE = 10,
	AREA_BIKER_BAR = 11,
	AREA_POLICE_STATION = 12,
	AREA_EVERYWHERE = 13,
	AREA_DIRT = 14,
	AREA_BLOOD = 15,
	AREA_OVALRING = 16,
	AREA_MALIBU_CLUB = 17,
	AREA_PRINT_WORKS = 18
}



----------------
-- PlayerInfo.h
----------------

-- Game states for when the game is running.
-- These are set depending on what has happened with the player.
-- These are what run when the player is playing, wasted, and busted.
player_info_enums.eWastedBustedState = {
	WBSTATE_PLAYING = 0,
	WBSTATE_WASTED = 1,
	WBSTATE_BUSTED = 2,
	WBSTATE_FAILED_CRITICAL_MISSION = 3,
}

player_info_enums.eBustedAudioState = {
	BUSTEDAUDIO_NONE = 0,
	BUSTEDAUDIO_LOADING = 1,
	BUSTEDAUDIO_DONE = 2
}

----------------
-- WeaponType.h
----------------

-- local eWeaponType = {
weapon_enums.eWeaponType = {
	WEAPONTYPE_UNARMED = 0,
	WEAPONTYPE_BRASSKNUCKLE = 1,
	WEAPONTYPE_SCREWDRIVER = 2,
	WEAPONTYPE_GOLFCLUB = 3,
	WEAPONTYPE_NIGHTSTICK = 4,
	WEAPONTYPE_KNIFE = 5,
	WEAPONTYPE_BASEBALLBAT = 6,
	WEAPONTYPE_HAMMER = 7,
	WEAPONTYPE_CLEAVER = 8,
	WEAPONTYPE_MACHETE = 9,
	WEAPONTYPE_KATANA = 10,
	WEAPONTYPE_CHAINSAW = 11,
	WEAPONTYPE_GRENADE = 12,
	WEAPONTYPE_DETONATOR_GRENADE = 13,
	WEAPONTYPE_TEARGAS = 14,
	WEAPONTYPE_MOLOTOV = 15,
	WEAPONTYPE_ROCKET = 16,
	WEAPONTYPE_COLT45 = 17,
	WEAPONTYPE_PYTHON = 18,
	WEAPONTYPE_SHOTGUN = 19,
	WEAPONTYPE_SPAS12_SHOTGUN = 20,
	WEAPONTYPE_STUBBY_SHOTGUN = 21,
	WEAPONTYPE_TEC9 = 22,
	WEAPONTYPE_UZI = 23,
	WEAPONTYPE_SILENCED_INGRAM = 24,
	WEAPONTYPE_MP5 = 25,
	WEAPONTYPE_M4 = 26,
	WEAPONTYPE_RUGER = 27,
	WEAPONTYPE_SNIPERRIFLE = 28,
	WEAPONTYPE_LASERSCOPE = 29,
	WEAPONTYPE_ROCKETLAUNCHER = 30,
	WEAPONTYPE_FLAMETHROWER = 31,
	WEAPONTYPE_M60 = 32,
	WEAPONTYPE_MINIGUN = 33,
	WEAPONTYPE_DETONATOR = 34,
	WEAPONTYPE_HELICANNON = 35,
	WEAPONTYPE_CAMERA = 36,
	WEAPONTYPE_TOTALWEAPONS = 37,
	-- WEAPONTYPE_HEALTH = 37,
	-- WEAPONTYPE_ARMOUR = 38,
	-- WEAPONTYPE_RAMMEDBYCAR = 39,
	-- WEAPONTYPE_RUNOVERBYCAR = 40,
	-- WEAPONTYPE_EXPLOSION = 41,
	-- WEAPONTYPE_UZI_DRIVEBY = 42,
	-- WEAPONTYPE_DROWNING = 43,
	-- WEAPONTYPE_FALL = 44,
	-- WEAPONTYPE_UNIDENTIFIED = 45,
	-- WEAPONTYPE_ANYMELEE = 46,
	-- WEAPONTYPE_ANYWEAPON = 47
}

weapon_enums.eWeaponSlot = {
	WEAPONSLOT_UNARMED = 0,
	WEAPONSLOT_MELEE = 1,
	WEAPONSLOT_PROJECTILE = 2,
	WEAPONSLOT_HANDGUN = 3,
	WEAPONSLOT_SHOTGUN = 4,
	WEAPONSLOT_SUBMACHINEGUN = 5,
	WEAPONSLOT_RIFLE = 6,
	WEAPONSLOT_HEAVY = 7,
	WEAPONSLOT_SNIPER = 8,
	WEAPONSLOT_OTHER = 9,
	TOTAL_WEAPON_SLOTS = 10
}

weapon_enums.eWeaponFire = {
	WEAPON_FIRE_MELEE = 0,
	WEAPON_FIRE_INSTANT_HIT = 1,
	WEAPON_FIRE_PROJECTILE = 2,
	WEAPON_FIRE_AREA_EFFECT = 3,
	WEAPON_FIRE_CAMERA = 4
}

weapon_enums.eWeaponState = {
	WEAPONSTATE_READY = 0,
	WEAPONSTATE_FIRING = 1,
	WEAPONSTATE_RELOADING = 2,
	WEAPONSTATE_OUT_OF_AMMO = 3,
	WEAPONSTATE_MELEE_MADECONTACT = 4
};

----------------
-- ModelIndices.h
----------------

-- Weapon model indices, for loading the weapon model.

weapon_enums.eWeaponModelIndices = {
	MI_BRASS_KNUCKLES = 259,
	MI_SCREWDRIVER = 260,
	MI_GOLFCLUB = 261,
	MI_NIGHTSTICK = 262,
	MI_KNIFE = 263,
	MI_BASEBALL_BAT = 264,
	MI_HAMMER = 265,
	MI_MEAT_CLEAVER = 266,
	MI_MACHETE = 267,
	MI_KATANA = 268,
	MI_CHAINSAW = 269,
	MI_GRENADE = 270,
	MI_TEARGAS = 271,
	MI_MOLOTOV = 272,
	MI_MISSILE = 273,
	MI_COLT45 = 274,
	MI_PYTHON = 275,
	MI_RUGER = 276,
	MI_SHOTGUN = 277,
	MI_SPAS12_SHOTGUN = 278,
	MI_STUBBY_SHOTGUN = 279,
	MI_M4 = 280,
	MI_TEC9 = 281,
	MI_UZI = 282,
	MI_SILENCEDINGRAM = 283,
	MI_MP5 = 284,
	MI_SNIPERRIFLE = 285,
	MI_LASERSCOPE = 286,
	MI_ROCKETLAUNCHER = 287,
	MI_FLAMETHROWER = 288,
	MI_M60 = 289,
	MI_MINIGUN = 290,
	MI_BOMB = 291,
	MI_CAMERA = 292,
	MI_FINGERS = 293,
	MI_MINIGUN2 = 294,
}

----------------
-- Garages.h
----------------

garage_enums.eGarageState = {
	GS_FULLYCLOSED = 0,
	GS_OPENED = 1,
	GS_CLOSING = 2,
	GS_OPENING = 3,
	GS_OPENEDCONTAINSCAR = 4,
	GS_CLOSEDCONTAINSCAR = 5,
	GS_AFTERDROPOFF = 6,
}

garage_enums.eGarageType = {
	GARAGE_NONE = 0,
	GARAGE_MISSION = 1,
	GARAGE_BOMBSHOP1 = 2,
	GARAGE_BOMBSHOP2 = 3,
	GARAGE_BOMBSHOP3 = 4,
	GARAGE_RESPRAY = 5,
	GARAGE_COLLECTORSITEMS = 6,
	GARAGE_COLLECTSPECIFICCARS = 7,
	GARAGE_COLLECTCARS_1 = 8,
	GARAGE_COLLECTCARS_2 = 9,
	GARAGE_COLLECTCARS_3 = 10,
	GARAGE_FORCARTOCOMEOUTOF = 11,
	GARAGE_60SECONDS = 12,
	GARAGE_CRUSHER = 13,
	GARAGE_MISSION_KEEPCAR = 14,
	GARAGE_FOR_SCRIPT_TO_OPEN = 15,
	GARAGE_HIDEOUT_ONE = 16,
	GARAGE_HIDEOUT_TWO = 17,
	GARAGE_HIDEOUT_THREE = 18,
	GARAGE_FOR_SCRIPT_TO_OPEN_AND_CLOSE = 19,
	GARAGE_KEEPS_OPENING_FOR_SPECIFIC_CAR = 20,
	GARAGE_MISSION_KEEPCAR_REMAINCLOSED = 21,
	GARAGE_COLLECTCARS_4 = 22,
	GARAGE_FOR_SCRIPT_TO_OPEN_FOR_CAR = 23,
	GARAGE_HIDEOUT_FOUR = 24,
	GARAGE_HIDEOUT_FIVE = 25,
	GARAGE_HIDEOUT_SIX = 26,
	GARAGE_HIDEOUT_SEVEN = 27,
	GARAGE_HIDEOUT_EIGHT = 28,
	GARAGE_HIDEOUT_NINE = 29,
	GARAGE_HIDEOUT_TEN = 30,
	GARAGE_HIDEOUT_ELEVEN = 31,
	GARAGE_HIDEOUT_TWELVE = 32
}

-- The enums for each of these are set in the code.
-- garage_enums.eTotalGarageVariables = {
	-- TOTAL_COLLECTCARS_GARAGES = 4,
	-- TOTAL_HIDEOUT_GARAGES = 12,
	-- TOTAL_COLLECTCARS_CARS = 6
-- }

-- For stored car flags, mostly for the saves.
-- This can be used once I get my json save/load system working.
garage_enums.eStoredCarFlags = {
	FLAG_BULLETPROOF = 0x1,
	FLAG_FIREPROOF = 0x2,
	FLAG_EXPLOSIONPROOF = 0x4,
	FLAG_COLLISIONPROOF = 0x8,
	FLAG_MELEEPROOF = 0x10,
}

----------------
-- Pickups.h
----------------

pickup_enums.ePickupType = {
	PICKUP_NONE = 0,
	PICKUP_IN_SHOP = 1,
	PICKUP_ON_STREET = 2,
	PICKUP_ONCE = 3,
	PICKUP_ONCE_TIMEOUT = 4,
	PICKUP_ONCE_TIMEOUT_SLOW = 5,
	PICKUP_COLLECTABLE1 = 6,
	PICKUP_IN_SHOP_OUT_OF_STOCK = 7,
	PICKUP_MONEY = 8,
	PICKUP_MINE_INACTIVE = 9,
	PICKUP_MINE_ARMED = 10,
	PICKUP_NAUTICAL_MINE_INACTIVE = 11,
	PICKUP_NAUTICAL_MINE_ARMED = 12,
	PICKUP_FLOATINGPACKAGE = 13,
	PICKUP_FLOATINGPACKAGE_FLOATING = 14,
	PICKUP_ON_STREET_SLOW = 15,
	PICKUP_ASSET_REVENUE = 16,
	PICKUP_PROPERTY_LOCKED = 17,
	PICKUP_PROPERTY_FORSALE = 18,
	-- PICKUP_NUMOFTYPES = 19
}

----------------
-- Radar.h
----------------
---


radar_enums.eBlipType = {
	BLIP_NONE,
	BLIP_CAR,
	BLIP_CHAR,
	BLIP_OBJECT,
	BLIP_COORD,
	BLIP_CONTACT_POINT
}

radar_enums.eBlipDisplay = {
	BLIP_DISPLAY_NEITHER = 0,
	BLIP_DISPLAY_MARKER_ONLY = 1,
	BLIP_DISPLAY_BLIP_ONLY = 2,
	BLIP_DISPLAY_BOTH = 3,
};

radar_enums.eRadarSprite = {
	RADAR_SPRITE_ENTITY_BLIP = -2,
	RADAR_SPRITE_COORD_BLIP = -1,
	RADAR_SPRITE_NONE = 0,
	RADAR_SPRITE_CENTRE = 1,
	RADAR_SPRITE_MAP_HERE = 2,
	RADAR_SPRITE_NORTH = 3,
	RADAR_SPRITE_AVERY = 4,
	RADAR_SPRITE_BIKER = 5,
	RADAR_SPRITE_CORTEZ = 6,
	RADAR_SPRITE_DIAZ = 7,
	RADAR_SPRITE_KENT = 8,
	RADAR_SPRITE_LAWYER = 9,
	RADAR_SPRITE_PHIL = 10,
	RADAR_SPRITE_BIKERS = 11,
	RADAR_SPRITE_BOATYARD = 12,
	RADAR_SPRITE_MALIBU_CLUB = 13,
	RADAR_SPRITE_CUBANS = 14,
	RADAR_SPRITE_FILM = 15,
	RADAR_SPRITE_GUN = 16,
	RADAR_SPRITE_HAITIANS = 17,
	RADAR_SPRITE_HARDWARE = 18,
	RADAR_SPRITE_SAVE = 19,
	RADAR_SPRITE_STRIP = 20,
	RADAR_SPRITE_ICE = 21,
	RADAR_SPRITE_KCABS = 22,
	RADAR_SPRITE_LOVEFIST = 23,
	RADAR_SPRITE_PRINTWORKS = 24,
	RADAR_SPRITE_PROPERTY = 25,
	RADAR_SPRITE_SUNYARD = 26,
	RADAR_SPRITE_SPRAY = 27,
	RADAR_SPRITE_TSHIRT = 28,
	RADAR_SPRITE_TOMMY = 29,
	RADAR_SPRITE_PHONE = 30,
	RADAR_SPRITE_RADIO_WILDSTYLE = 31,
	RADAR_SPRITE_RADIO_FLASH = 32,
	RADAR_SPRITE_RADIO_KCHAT = 33,
	RADAR_SPRITE_RADIO_FEVER = 34,
	RADAR_SPRITE_RADIO_VROCK = 35,
	RADAR_SPRITE_RADIO_VCPR = 36,
	RADAR_SPRITE_RADIO_ESPANTOSO = 37,
	RADAR_SPRITE_RADIO_EMOTION = 38,
	RADAR_SPRITE_RADIO_WAVE = 39,
-- MAP_ENHANCEMENTS
	RADAR_SPRITE_WAYPOINT = 40,
-- MAP_ENHANCEMENTS

	RADAR_SPRITE_COUNT = 41
}

radar_enums.eRadarTraces = {
	RADAR_TRACE_RED = 0,
	RADAR_TRACE_GREEN = 1,
	RADAR_TRACE_LIGHT_BLUE = 2,
	RADAR_TRACE_GRAY = 3,
	RADAR_TRACE_YELLOW = 4,
	RADAR_TRACE_MAGENTA = 5,
	RADAR_TRACE_CYAN = 6
}


radar_enums.eRadarModes = {
	BLIP_MODE_TRIANGULAR_UP = 0,
	BLIP_MODE_TRIANGULAR_DOWN,
	BLIP_MODE_SQUARE,
}


----------------
--- Weather.h
----------------

weather_enums.eWeatherType = {
	-- WEATHER_RANDOM = -1,
	WEATHER_SUNNY = 0,
	WEATHER_CLOUDY = 1,
	WEATHER_RAINY = 2,
	WEATHER_FOGGY = 3,
	WEATHER_EXTRA_SUNNY = 4,
	WEATHER_HURRICANE = 5,
	WEATHER_TOTAL = 6,

	-- WEATHER_EXTRACOLOURS = 6
}

----------------
-- ZoneCull.h
----------------

zone_enums.eZoneAttribs = {
	ATTRZONE_CAMCLOSEIN		= 1,
	ATTRZONE_STAIRS			= 2,
	ATTRZONE_1STPERSON		= 4,
	ATTRZONE_NORAIN			= 8,
	ATTRZONE_NOPOLICE		= 0x10,
	ATTRZONE_NOTCULLZONE		= 0x20,
	ATTRZONE_DOINEEDCOLLISION	= 0x40,
	ATTRZONE_SUBWAYVISIBLE		= 0x80,
	ATTRZONE_POLICEABANDONCARS	= 0x100,
	ATTRZONE_ROOMFORAUDIO		= 0x200,
	ATTRZONE_WATERFUDGE		= 0x400,
}



----------------
-- PedType.h
----------------

-- enum ePedType
-- {
-- 	PEDTYPE_PLAYER1,
-- 	PEDTYPE_PLAYER2,
-- 	PEDTYPE_PLAYER3,
-- 	PEDTYPE_PLAYER4,
-- 	PEDTYPE_CIVMALE,
-- 	PEDTYPE_CIVFEMALE,
-- 	PEDTYPE_COP,
-- 	PEDTYPE_GANG1,
-- 	PEDTYPE_GANG2,
-- 	PEDTYPE_GANG3,
-- 	PEDTYPE_GANG4,
-- 	PEDTYPE_GANG5, -- Security - hardcoded
-- 	PEDTYPE_GANG6,
-- 	PEDTYPE_GANG7, -- Vercetti gang - hardcoded
-- 	PEDTYPE_GANG8,
-- 	PEDTYPE_GANG9,
-- 	PEDTYPE_EMERGENCY,
-- 	PEDTYPE_FIREMAN,
-- 	PEDTYPE_CRIMINAL,
-- 	PEDTYPE_UNUSED1,
-- 	PEDTYPE_PROSTITUTE,
-- 	PEDTYPE_SPECIAL,
-- 	PEDTYPE_UNUSED2,

-- 	NUM_PEDTYPES
-- };


----------------
-- Ped.h
----------------

-- PedState

	-- PED_NONE,
	-- PED_IDLE,
	-- PED_LOOK_ENTITY,
	-- PED_LOOK_HEADING,
	-- PED_WANDER_RANGE,
	-- PED_WANDER_PATH,
	-- PED_SEEK_POS,
	-- PED_SEEK_ENTITY,
	-- PED_FLEE_POS,
	-- PED_FLEE_ENTITY,
	-- PED_PURSUE,
	-- PED_FOLLOW_PATH,
	-- PED_SNIPER_MODE,
	-- PED_ROCKET_MODE,
	-- PED_DUMMY,
	-- PED_PAUSE,
	-- PED_ATTACK,
	-- PED_FIGHT,
	-- PED_FACE_PHONE,
	-- PED_MAKE_CALL,
	-- PED_CHAT,
	-- PED_MUG,
	-- PED_AIM_GUN,
	-- PED_AI_CONTROL,
	-- PED_SEEK_CAR,
	-- PED_SEEK_IN_BOAT,
	-- PED_FOLLOW_ROUTE,
	-- PED_CPR,
	-- PED_SOLICIT,
	-- PED_BUY_ICECREAM,
	-- PED_INVESTIGATE,
	-- PED_STEP_AWAY,
	-- PED_ON_FIRE,
	-- PED_SUN_BATHE,
	-- PED_FLASH,
	-- PED_JOG,
	-- PED_ANSWER_MOBILE,

	-- PED_UNKNOWN,

	-- PED_STATES_NO_AI,

	-- PED_ABSEIL,
	-- PED_SIT,
	-- PED_JUMP,
	-- PED_FALL,
	-- PED_GETUP,
	-- PED_STAGGER,
	-- PED_DIVE_AWAY,

	-- PED_STATES_NO_ST,
	-- PED_ENTER_TRAIN,
	-- PED_EXIT_TRAIN,
	-- PED_ARREST_PLAYER,

	-- PED_DRIVING,
	-- PED_PASSENGER,
	-- PED_TAXI_PASSENGER,
	-- PED_OPEN_DOOR,
	-- PED_DIE,
	-- PED_DEAD,
	-- PED_CARJACK,
	-- PED_DRAG_FROM_CAR,
	-- PED_ENTER_CAR,
	-- PED_STEAL_CAR,
	-- PED_EXIT_CAR,
	-- PED_HANDS_UP,
	-- PED_ARRESTED,
	-- PED_DEPLOY_STINGER

-- eMoveState
	-- PEDMOVE_NONE,
	-- PEDMOVE_STILL,
	-- PEDMOVE_WALK,
	-- PEDMOVE_JOG,
	-- PEDMOVE_RUN,
	-- PEDMOVE_SPRINT,
	-- PEDMOVE_THROWN

-- eWaitState
	-- WAITSTATE_FALSE,
	-- WAITSTATE_TRAFFIC_LIGHTS,
	-- WAITSTATE_CROSS_ROAD,
	-- WAITSTATE_CROSS_ROAD_LOOK,
	-- WAITSTATE_LOOK_PED,
	-- WAITSTATE_LOOK_SHOP,
	-- WAITSTATE_LOOK_ACCIDENT,
	-- WAITSTATE_FACEOFF_GANG,
	-- WAITSTATE_DOUBLEBACK,
	-- WAITSTATE_HITWALL,
	-- WAITSTATE_TURN180,
	-- WAITSTATE_SURPRISE,
	-- WAITSTATE_STUCK,
	-- WAITSTATE_LOOK_ABOUT,
	-- WAITSTATE_PLAYANIM_DUCK,
	-- WAITSTATE_PLAYANIM_COWER,
	-- WAITSTATE_PLAYANIM_TAXI,
	-- WAITSTATE_PLAYANIM_HANDSUP,
	-- WAITSTATE_PLAYANIM_HANDSCOWER,
	-- WAITSTATE_PLAYANIM_CHAT,
	-- WAITSTATE_FINISH_FLEE,
	-- WAITSTATE_SIT_DOWN,
	-- WAITSTATE_SIT_DOWN_RVRS,
	-- WAITSTATE_SIT_UP,
	-- WAITSTATE_SIT_IDLE,
	-- WAITSTATE_USE_ATM,
	-- WAITSTATE_SUN_BATHE_PRE,
	-- WAITSTATE_SUN_BATHE_DOWN,
	-- WAITSTATE_SUN_BATHE_IDLE,
	-- WAITSTATE_RIOT,
	-- WAITSTATE_FAST_FALL,
	-- WAITSTATE_BOMBER,
	-- WAITSTATE_STRIPPER,
	-- WAITSTATE_GROUND_ATTACK,
	-- WAITSTATE_LANCESITTING,
	-- WAITSTATE_PLAYANIM_HANDSUP_SIMPLE,

-- eObjective

    -- "OBJECTIVE_NONE"
	-- OBJECTIVE_WAIT_ON_FOOT,
	-- OBJECTIVE_WAIT_ON_FOOT_FOR_COP,
	-- OBJECTIVE_FLEE_ON_FOOT_TILL_SAFE,
	-- OBJECTIVE_GUARD_SPOT,
	-- OBJECTIVE_GUARD_AREA,
	-- OBJECTIVE_WAIT_IN_CAR,
	-- OBJECTIVE_WAIT_IN_CAR_THEN_GET_OUT,
	-- OBJECTIVE_KILL_CHAR_ON_FOOT,
	-- OBJECTIVE_KILL_CHAR_ANY_MEANS,
	-- OBJECTIVE_FLEE_CHAR_ON_FOOT_TILL_SAFE,
	-- OBJECTIVE_FLEE_CHAR_ON_FOOT_ALWAYS,
	-- OBJECTIVE_GOTO_CHAR_ON_FOOT,
	-- OBJECTIVE_GOTO_CHAR_ON_FOOT_WALKING,
	-- OBJECTIVE_HASSLE_CHAR,
	-- OBJECTIVE_FOLLOW_CHAR_IN_FORMATION,
	-- OBJECTIVE_LEAVE_CAR,
	-- OBJECTIVE_ENTER_CAR_AS_PASSENGER,
	-- OBJECTIVE_ENTER_CAR_AS_DRIVER,
	-- OBJECTIVE_FOLLOW_CAR_IN_CAR,
	-- OBJECTIVE_FIRE_AT_OBJECT_FROM_VEHICLE,
	-- OBJECTIVE_DESTROY_OBJECT,
	-- OBJECTIVE_DESTROY_CAR,
	-- OBJECTIVE_GOTO_AREA_ANY_MEANS,
	-- OBJECTIVE_GOTO_AREA_ON_FOOT,
	-- OBJECTIVE_RUN_TO_AREA,
	-- OBJECTIVE_GOTO_AREA_IN_CAR,
	-- OBJECTIVE_FOLLOW_CAR_ON_FOOT_WITH_OFFSET,
	-- OBJECTIVE_GUARD_ATTACK,
	-- OBJECTIVE_SET_LEADER,
	-- OBJECTIVE_FOLLOW_ROUTE,
	-- OBJECTIVE_SOLICIT_VEHICLE,
	-- OBJECTIVE_HAIL_TAXI,
	-- OBJECTIVE_CATCH_TRAIN,
	-- OBJECTIVE_BUY_ICE_CREAM,
	-- OBJECTIVE_STEAL_ANY_CAR,
	-- OBJECTIVE_STEAL_ANY_MISSION_CAR,
	-- OBJECTIVE_MUG_CHAR,
	-- OBJECTIVE_LEAVE_CAR_AND_DIE,
	-- OBJECTIVE_GOTO_SEAT_ON_FOOT,
	-- OBJECTIVE_GOTO_ATM_ON_FOOT,
	-- OBJECTIVE_FLEE_CAR,
	-- OBJECTIVE_SUN_BATHE,
	-- OBJECTIVE_GOTO_BUS_STOP_ON_FOOT,
	-- OBJECTIVE_GOTO_PIZZA_ON_FOOT,
	-- OBJECTIVE_GOTO_SHELTER_ON_FOOT,
	-- OBJECTIVE_AIM_GUN_AT,
	-- OBJECTIVE_WANDER,
	-- OBJECTIVE_WAIT_ON_FOOT_AT_SHELTER,
	-- OBJECTIVE_SPRINT_TO_AREA,
	-- OBJECTIVE_KILL_CHAR_ON_BOAT,
	-- OBJECTIVE_SOLICIT_FOOT,
	-- OBJECTIVE_WAIT_ON_FOOT_AT_BUS_STOP,
	-- OBJECTIVE_GOTO_ICE_CREAM_VAN_ON_FOOT,
	-- OBJECTIVE_WAIT_ON_FOOT_AT_ICE_CREAM_VAN,
	-- OBJ_55,
	-- OBJ_56,
	-- OBJ_57,
	-- OBJ_58,
	-- OBJ_59
